apiVersion: apps/v1
kind: Deployment
metadata:
  name: qhello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qhello
  template:
    metadata:
      labels:
        app: qhello
    spec:
      containers:
        - name: qhello
          image: us.icr.io/dom-test/qhello:2
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
